version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: cinema-nginx-proxy2
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  movies:
    build: ./movies
    image: moviesapp/movies
    container_name: movies2
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: movies.local

  approvereviews:
    build: ./approvereviews
    image: moviesapp/approvereviews
    container_name: approvereviews
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: approvereviews.local

  db:
    image: mongo:3.3
    container_name: cinema-db222
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup:rw
